name: anilist_ui
description: UI for anilist.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_secure_storage: ^9.0.0
  graphql_flutter: ^5.1.2
  provider: ^6.0.5
  pretty_json: ^2.0.0
  google_fonts: ^4.0.4
  go_router: ^11.1.4
  basic_utils: ^5.5.4
  intl: ^0.18.1
  html: ^0.15.4
  url_launcher: ^6.1.14
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  graphql_codegen: ^0.12.2
  build_runner: ^2.4.6
  go_router_builder: ^2.3.3
  build_verify: ^3.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
